// middleware.ts
import { withAuth } from "next-auth/middleware";
import { NextResponse } from "next/server";

export default withAuth(
  // `withAuth` augments your AuthOptions with explicit middleware options
  function middleware(req) {
    // You can add custom middleware logic here if needed.
    // For example, checking user roles or permissions after authentication.
    // The authenticated user's token is available at `req.nextauth.token`.
    console.log("Middleware token:", req.nextauth.token);

    // Example: Redirect to a different page based on user role (requires token to have a 'role' property)
    // if (req.nextUrl.pathname === "/admin" && req.nextauth.token?.role !== "admin") {
    //   return NextResponse.redirect(new URL("/dashboard", req.url));
    // }

    // If the `authorized` callback below returns true,
    // and no custom redirect is performed here,
    // the user will proceed to the requested page.
  },
  {
    callbacks: {
      authorized: ({ token }) => {
        // This is the key part for authentication.
        // Return true if the user is authorized, false otherwise.
        // `token` is the JWT token generated by NextAuth.js.
        // If the token exists, the user is considered authenticated.
        // next-auth handles token expiration internally; if the token is expired,
        // it will be null or undefined here.
        console.log("Authorized callback token:", token);
        return !!token; // Return true if the token exists (user is authenticated)
      }
    },
    // Specify the path to your sign-in page.
    // If the `authorized` callback returns false for a matched route,
    // the user will be automatically redirected to this page.
    pages: {
      signIn: "/auth/login" // Adjust this path to your login page
    }
  }
);

// Specify which paths the middleware should apply to.
export const config = {
  // This matcher will apply the middleware to the root path "/",
  // and all paths under "/dashboard" and "/settings".
  // Adjust this array to include all routes that require authentication.
  // Routes NOT included here will be publicly accessible.
  matcher: ["/", "/dashboard/:path*", "/settings/:path*"] // Add other protected paths here
};
