export const types = {
  addUser: "[User] Add User",
  updateUser: "[User] Update User",
  deleteUser: "[User] Delete User",
  usersLoaded: "[User] Users Loaded",

  addWorker: "[Worker] Add worker",
  updateWorker: "[Worker] Update worker",
  deleteWorker: "[Worker] Delete worker",
  workersLoaded: "[Worker] Workers Loaded",
  selectedWorker: "[Worker] Worker selected",

  addWarehouse: "[Warehouse] Add Warehouse",
  updateWarehouse: "[Warehouse] Update Warehouse",
  deleteWarehouse: "[Warehouse] Delete Warehouse",
  warehousesLoaded: "[Warehouse] Warehouses Loaded",
  selectedWarehouse: "[Warehouse] Warehouse selected",

  addMaterial: "[Material] Add Material",
  updateMaterial: "[Material] Update Material",
  deleteMaterial: "[Material] Delete Material",
  materialsLoaded: "[Material] Materials Loaded",
  selectedMaterial: "[Material] Material selected",
  lowExistencesMaterials: "[Material] Low existences materials Loaded",
  editMaterial: "[Material] Edit material",

  addNomenclator: "[Nomenclator] Add Nomenclator",
  updateNomenclator: "[Nomenclator] Update Nomenclator",
  deleteNomenclator: "[Nomenclator] Delete Nomenclator",
  nomenclatorsLoaded: "[Nomenclator] Nomenclators Loaded",
  selectedNomenclator: "[Nomenclator] Nomenclator selected",

  addClientNomenclator: "[Nomenclator] Add Client Nomenclator",
  updateClientNomenclator: "[Nomenclator] Update Client Nomenclator",
  deleteClientNomenclator: "[Nomenclator] Delete Client Nomenclator",
  clientNomenclatorsLoaded: "[Nomenclator] Client Nomenclators Loaded",

  addRepresentativeNomenclator: "[Nomenclator] Add Representative Nomenclator",
  updateRepresentativeNomenclator: "[Nomenclator] Update Representative Nomenclator",
  deleteRepresentativeNomenclator: "[Nomenclator] Delete Representative Nomenclator",
  representativeNomenclatorsLoaded: "[Nomenclator] Representative Nomenclators Loaded",

  addCostSheet: "[CostSheet] Add CostSheet",
  updateCostSheet: "[CostSheet] Update CostSheet",
  deleteCostSheet: "[CostSheet] Delete CostSheet",
  costSheetsLoaded: "[CostSheet] CostSheets Loaded",
  selectedCostSheet: "[CostSheet] Load Selected Cost Sheet",

  addServiceFee: "[ServiceFee] Add Service Fee",
  updateServiceFee: "[ServiceFee] Update Service Fee",
  deleteServiceFee: "[ServiceFee] Delete Service Fee",
  serviceFeesLoaded: "[ServiceFee] Service Fees Loaded",
  selectedServiceFee: "[ServiceFee] Load Selected Service Fee",

  addServiceFeeTask: "[ServiceFee] Add Service Fee Task",
  updateServiceFeeTask: "[ServiceFee] Update Service Fee Task",
  deleteServiceFeeTask: "[ServiceFee] Delete Service Fee Task",
  serviceFeesTasksLoaded: "[ServiceFee] Service Fees Tasks Loaded",

  addProject: "[Project] Add Project",
  updateProject: "[Project] Update Project",
  deleteProject: "[Project] Delete Project",
  projectsLoaded: "[Project] Projects Loaded",
  loadSelectedProject: "[Project] Load Selected Project",
  editItemList: "[Project] Edit Item in Project",

  addOffer: "[Offer] Add Offer",
  updateOffer: "[Offer] Update Offer",
  deleteOffer: "[Offer] Delete Offer",
  offersLoaded: "[Offer] Offers Loaded",
  selectedOffer: "[Offer] Offer Selected",
  setCurrentItem: "[Offer] Add Item to State",
  deleteItem: "[Offer] Delete an Item From the Offer",
  editItem: "[Offer] Edit an Item From the Offer",
  selectedItem: "[Offer] Item Selected",
  clearOffer: "[Offer] Clear Offer",
  setFinalOffer: "[Offer] Set Offer as Final",
  editActivityList: "[Offer] Edit Activity in Offer",
  selectedActivity: "[Offer] Activity Selected",

  setCurrencyChange: "[Global] Set Currency Change",

  updateServiceFeeAuxiliary: "[ServiceFeeAuxiliary] Update Service Fee Auxiliary",
  serviceFeeAuxiliaryLoaded: "[ServiceFeeAuxiliary] Load Service Fee Auxiliary"
};
